"""Copilot SDK client for the agent runtime.

This module wraps the GitHub Copilot SDK to provide AI-powered
code generation and modification capabilities.
"""

import json
import logging
import os

logger = logging.getLogger(__name__)


class CopilotClient:
    """Client for interacting with GitHub Copilot SDK."""

    def __init__(
        self,
        system_prompt: str | None = None,
        github_token: str | None = None,
    ) -> None:
        self.system_prompt = system_prompt or "You are a helpful coding assistant."
        self.github_token = github_token or os.environ.get("GITHUB_TOKEN", "")
        self._sdk = None

    async def initialize(self) -> None:
        """Initialize the Copilot SDK client.

        This lazily imports and sets up the SDK so the module can be
        imported even when the SDK is not installed (e.g., during testing).
        """
        try:
            from copilot_sdk import CopilotSDK

            self._sdk = CopilotSDK(token=self.github_token)
            logger.info("Copilot SDK initialized successfully")
        except ImportError:
            logger.warning("copilot-sdk not installed — running in stub mode")
            self._sdk = None

    async def execute_instruction(
        self,
        instruction: str,
        context: dict | None = None,
    ) -> dict:
        """Execute a coding instruction using Copilot.

        Args:
            instruction: The user's coding instruction.
            context: Optional context (file list, repo info, etc.)

        Returns:
            dict with keys: response, files_modified, summary
        """
        if self._sdk is None:
            # Stub mode — generate template-based code for pipeline testing
            return self._stub_execute(instruction)

        messages = [
            {"role": "system", "content": self._build_system_prompt(context)},
            {"role": "user", "content": instruction},
        ]

        try:
            response = await self._sdk.chat(messages=messages)
            return {
                "response": response.get("content", ""),
                "files_modified": response.get("files_modified", []),
                "summary": self._extract_summary(response),
            }
        except Exception:
            logger.exception("Copilot SDK execution failed")
            return {
                "response": "",
                "files_modified": [],
                "summary": "Error: Copilot SDK execution failed",
            }

    def _build_system_prompt(self, context: dict | None = None) -> str:
        """Build the full system prompt with optional context."""
        parts = [self.system_prompt]

        if context:
            if "repo_info" in context:
                parts.append(f"\nRepository: {context['repo_info']}")
            if "file_list" in context:
                parts.append(f"\nFiles in workspace:\n{json.dumps(context['file_list'], indent=2)}")

        parts.append("\n\nAfter making changes, provide a brief summary of what was modified.")
        return "\n".join(parts)

    @staticmethod
    def _extract_summary(response: dict) -> str:
        """Extract a summary from the SDK response."""
        content = response.get("content", "")
        # Take first paragraph as summary
        lines = content.strip().split("\n")
        summary_lines = []
        for line in lines:
            if line.strip() == "" and summary_lines:
                break
            summary_lines.append(line)
        return " ".join(summary_lines)[:500]

    @staticmethod
    def _stub_execute(instruction: str) -> dict:
        """Generate template-based output for pipeline testing when SDK is unavailable.

        Instead of returning a simple placeholder, this creates a minimal
        README.md so that the git commit / push / PR pipeline can be
        exercised end-to-end even without the real Copilot SDK.
        """
        import os
        from pathlib import Path

        workspace = Path(os.environ.get("REPO_DIR", "/workspace/repo"))
        stub_file = workspace / "AGENT_OUTPUT.md"
        content = (
            f"# Agent Output\n\n"
            f"## Instruction\n\n{instruction}\n\n"
            f"## Result\n\n"
            f"This file was generated by the pioyan-chat agent runtime\n"
            f"running in **stub mode** (Copilot SDK not available).\n\n"
            f"The pipeline executed successfully.\n"
        )

        files_modified: list[str] = []
        try:
            stub_file.write_text(content, encoding="utf-8")
            files_modified.append(str(stub_file.relative_to(workspace)))
            logger.info("Stub mode: wrote %s", stub_file)
        except OSError as exc:
            logger.warning("Stub mode: could not write file: %s", exc)

        return {
            "response": content,
            "files_modified": files_modified,
            "summary": f"[stub] Generated AGENT_OUTPUT.md for: {instruction[:120]}",
        }
