"""Agent runtime main entry point — HTTP server running inside each container.

This service accepts coding instructions from the pioyan-chat backend,
executes them using the Copilot SDK, commits results, and returns responses.
"""

import json
import logging
import os
import uuid
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")
logger = logging.getLogger("agent-runtime")

# Configuration from environment
REPO_URL = os.environ.get("REPO_URL", "")
BRANCH = os.environ.get("BRANCH", "main")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
AGENT_ID = os.environ.get("AGENT_ID", "unknown")
CHANNEL_ID = os.environ.get("CHANNEL_ID", "unknown")
SYSTEM_PROMPT = os.environ.get("SYSTEM_PROMPT", "You are a helpful coding assistant.")
PORT = int(os.environ.get("AGENT_PORT", "8080"))


class TaskHandler(BaseHTTPRequestHandler):
    """HTTP handler for receiving and processing coding tasks."""

    copilot = None
    git_ops = None
    initialized = False

    def do_POST(self):
        if self.path == "/task":
            self._handle_task()
        elif self.path == "/health":
            self._respond(200, {"status": "ok"})
        else:
            self._respond(404, {"error": "Not found"})

    def do_GET(self):
        if self.path == "/health":
            self._respond(200, {"status": "ok", "agent_id": AGENT_ID})
        else:
            self._respond(404, {"error": "Not found"})

    def _handle_task(self):
        """Process a coding task."""
        try:
            content_length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(content_length))
        except (json.JSONDecodeError, ValueError):
            self._respond(400, {"error": "Invalid JSON"})
            return

        instruction = body.get("instruction", "")
        if not instruction:
            self._respond(400, {"error": "Missing instruction"})
            return

        task_id = body.get("task_id", str(uuid.uuid4()))
        auto_commit = body.get("auto_commit", True)
        create_pr = body.get("create_pr", True)

        try:
            import asyncio

            result = asyncio.run(self._execute_task(instruction, task_id, auto_commit, create_pr))
            self._respond(200, result)
        except Exception as e:
            logger.exception("Task execution failed")
            self._respond(
                500,
                {
                    "status": "failed",
                    "task_id": task_id,
                    "error": str(e),
                },
            )

    async def _execute_task(
        self,
        instruction: str,
        task_id: str,
        auto_commit: bool,
        create_pr: bool,
    ) -> dict[str, Any]:
        """Execute a coding instruction end-to-end."""
        # Ensure initialization
        if not TaskHandler.initialized:
            await self._initialize()

        # Create a working branch
        branch_name = f"agent/{AGENT_ID}/{task_id[:8]}"
        TaskHandler.git_ops.create_branch(branch_name)

        # Execute instruction via Copilot SDK
        result = await TaskHandler.copilot.execute_instruction(
            instruction=instruction,
            context={"repo_info": f"{REPO_URL} (branch: {BRANCH})"},
        )

        response_data = {
            "status": "completed",
            "task_id": task_id,
            "response": result["response"],
            "summary": result["summary"],
            "files_modified": result["files_modified"],
            "commit_sha": None,
            "pr_url": None,
            "branch_name": branch_name,
        }

        # Auto-commit if changes were made
        if auto_commit:
            commit_msg = f"feat: {instruction[:72]}\n\nAgent: {AGENT_ID}\nTask: {task_id}"
            sha = TaskHandler.git_ops.commit_all(commit_msg)
            response_data["commit_sha"] = sha

            if sha and create_pr:
                TaskHandler.git_ops.push(branch_name)
                pr_url = TaskHandler.git_ops.create_pr(
                    title=f"[Agent] {instruction[:100]}",
                    body=f"## Coding Task\n\n{instruction}\n\n## Summary\n\n{result['summary']}\n\n---\n_Auto-generated by pioyan-chat agent `{AGENT_ID}`_",
                    base=BRANCH,
                )
                response_data["pr_url"] = pr_url

        return response_data

    async def _initialize(self):
        """One-time initialization: clone repo, init Copilot SDK."""
        from copilot_client import CopilotClient
        from git_ops import GitOps

        logger.info("Initializing agent runtime...")

        # Clone repository
        TaskHandler.git_ops = GitOps()
        TaskHandler.git_ops.clone(REPO_URL, BRANCH, GITHUB_TOKEN)

        # Initialize Copilot SDK
        TaskHandler.copilot = CopilotClient(
            system_prompt=SYSTEM_PROMPT,
            github_token=GITHUB_TOKEN,
        )
        await TaskHandler.copilot.initialize()

        TaskHandler.initialized = True
        logger.info("Agent runtime initialized successfully")

    def _respond(self, status: int, body: dict):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(body).encode())

    def log_message(self, format, *args):
        logger.info(format, *args)


def main():
    """Start the agent runtime HTTP server."""
    logger.info(f"Starting agent runtime on port {PORT} (agent={AGENT_ID})")
    server = HTTPServer(("0.0.0.0", PORT), TaskHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logger.info("Agent runtime shutting down")
        server.shutdown()


if __name__ == "__main__":
    main()
